[tool.isort]
profile = "black"

[tool.documatic]
name = "Doculog"
srcdir = "doculog"
docdir = "."

[tool.doculog]
changelog = "CHANGELOG"
local = true

[tool.doculog.categories]
create_section = true
"Feat:" = "New Features Added:"
